apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-ops-poc
  namespace: argocd
spec:
  project: git-ops-project
  source:
    repoURL: https://github.com/apesconsole/git-ops-poc.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  revisionHistoryLimit: 1  