name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Build Docker Image
        run: |
          docker build -t git-ops-poc .
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push Docker Image
        run: |
          docker tag git-ops-poc:latest apesconsole/git-ops-poc:latest
          docker push apesconsole/git-ops-poc:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Set up Kubernetes kubeconfig
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
       
      - name: Create Kubernetes Secret for MY_SECRET
        run: |
          kubectl create secret generic my.secret --namespace=poc --from-literal=MY_SECRET=$(echo $env:MY_SECRET) --dry-run=client -o yaml | kubectl apply -f -
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          
      - name: Delete existing Docker Hub Secret
        run: |
          kubectl delete secret apes-dockerhub-secret --ignore-not-found=true

      - name: Create Docker Hub Secret in Kubernetes
        run: |
          kubectl create secret docker-registry apes-dockerhub-secret --docker-server=https://index.docker.io/v1/ --docker-username=$(echo env:DOCKER_USERNAME) --docker-password=$(echo env:DOCKER_PASSWORD) --dry-run=client -o yaml | kubectl apply -f -
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
